language: php

arch:
  - amd64
  - arm64

os: linux

php:
  - "7.2"

services:
  - docker

before_install:
  - docker login --username $DOCKER_USER --password $DOCKER_PASSWORD $DOCKER_REGISTRY

script:
  - cd php
  - ./build.sh $TRAVIS_PHP_VERSION $DOCKER_USER $DOCKER_PASSWORD $DOCKER_REGISTRY
