language: php

arch:
  - amd64
  - arm64

php:
  - "5.6"
  - "7.0"
  - "7.1"
  - "7.2"
  - "7.3"

sudo: required

services:
  - docker

before_install:
  - docker login --username $DOCKER_USER --password $DOCKER_PASSWORD $DOCKER_REGISTRY

script:
  - cd php
  - ./build.sh $TRAVIS_PHP_VERSION $DOCKER_USER $DOCKER_PASSWORD $DOCKER_REGISTRY
