language: php

php:
  - "7.2"

sudo: required

services:
  - docker

before_install:
  - docker login --username $DOCKER_USER --password $DOCKER_PASSWORD $DOCKER_REGISTRY

script:
  - cd php
  - ./build.sh 5.6 $DOCKER_USER $DOCKER_PASSWORD $DOCKER_REGISTRY
  - ./build.sh 7.0 $DOCKER_USER $DOCKER_PASSWORD $DOCKER_REGISTRY
  - ./build.sh 7.1 $DOCKER_USER $DOCKER_PASSWORD $DOCKER_REGISTRY
  - ./build.sh 7.2 $DOCKER_USER $DOCKER_PASSWORD $DOCKER_REGISTRY
