language: python

dist: bionic

python:
  - 3.6

env:
  - PHP_VERSION=5.6
  - PHP_VERSION=7.0
  - PHP_VERSION=7.1
  - PHP_VERSION=7.2
  - PHP_VERSION=7.3
  - PHP_VERSION=7.4
  - PHP_VERSION=8.0

before_install:
  - ./install-buildah-ubuntu.sh
  - pip install -r requirements.txt
  - buildah login --username $DOCKER_USER --password $DOCKER_PASSWORD $DOCKER_REGISTRY

script:
  - python ./build.py $PHP_VERSION

